name: dongphuc296web
description: Dong phuc 296 web
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  get:
  dual_screen: ^1.0.3
  scoped_model: ^2.0.0-nullsafety.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  google_fonts: ^2.3.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  cloud_firestore_web: ^2.8.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - packages/web_images/
    - packages/product_images/
