// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeNvfdAzrEZ2NgW5jqkqzj6rVZh3DegM',
    appId: '1:1042952740806:web:7dc4ecc288f41c699e1cc7',
    messagingSenderId: '1042952740806',
    projectId: 'dongphuc296web',
    authDomain: 'dongphuc296web.firebaseapp.com',
    storageBucket: 'dongphuc296web.appspot.com',
    measurementId: 'G-JPN1D5H02E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRUQz_TVgayXlUX2-4x1YL3qgNOd-jGE',
    appId: '1:1042952740806:android:ad1615067d49980f9e1cc7',
    messagingSenderId: '1042952740806',
    projectId: 'dongphuc296web',
    storageBucket: 'dongphuc296web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_udDIbk-SxrQYxGl1u2zi3dcRwvdwdM',
    appId: '1:1042952740806:ios:e50ef4250a7922909e1cc7',
    messagingSenderId: '1042952740806',
    projectId: 'dongphuc296web',
    storageBucket: 'dongphuc296web.appspot.com',
    iosClientId: '1042952740806-ulrdddu406o5ip0emr84am8pah59f662.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.dongphuc296web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_udDIbk-SxrQYxGl1u2zi3dcRwvdwdM',
    appId: '1:1042952740806:ios:e50ef4250a7922909e1cc7',
    messagingSenderId: '1042952740806',
    projectId: 'dongphuc296web',
    storageBucket: 'dongphuc296web.appspot.com',
    iosClientId: '1042952740806-ulrdddu406o5ip0emr84am8pah59f662.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.dongphuc296web',
  );
}
